#
# 
# composee para bildar localstack
# 
#

localstack:
  container_name: "localstack-service"
  image: localstack/localstack
  ports:
    - "4500-4600:4500-4600"
  environment:
      - SERVICES=ec2,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
  volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
